services:
  po-watcher:
    build: .
    image: po-watcher:latest
    container_name: po-watcher
    restart: unless-stopped

    # Make the container use your AD DNS and suffix
    dns:
      - 192.168.142.40           # dsadbat02
      - 192.168.142.39         #dsadbat01
    dns_search:
      - dscontainer.local

    environment:
      # JDE
      JDE_HOST: "http://r24uxpd02.dscontainer.local:7005/"
      JDE_ORCH_NAME: "PG03_ORCH_P5542101CreatePO"
      JDE_WRAP_INPUTS: "false"
      JDE_USER: "${JDE_USER}"
      JDE_PASS: "${JDE_PASS}"
      JDE_ENV: "${JDE_ENV}"
      JDE_ROLE: "${JDE_ROLE:-*}"
      JDE_DEVICE: "PO-Auto-Docker"

      WATCH_DIR_BASE: "/input"              # read-only source
      CONFIG_PATH: "/local_files/config.json"
      WORK_DIR: "/work/pdf_frames"
      PROCESSED_DIR: "/data/processed"
      ERROR_DIR: "/data/error"
      SQL_CONN_STR: "${SQL_CONN_STR}"
      WATCH_USE_POLLING: "1"
      POLL_INTERVAL: "15.0"

    
    volumes:
      - input_smb:/input:ro
      - local_files:/local_files:ro
      - ./data:/data
      - ./frames:/work/pdf_frames

    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  input_smb:
    driver: local
    driver_opts:
      type: cifs
      device: "//dsfile4/shared/CUSTOMERS/"
      o: "username=${SMB_USER},password=${SMB_PASS},domain=${SMB_DOMAIN:-},uid=1000,gid=1000,vers=3.0,file_mode=0444,dir_mode=0555"

  local_files:
    driver: local
    driver_opts:
      type: none
      device: "C:/DockerContainers/POAutomation"
      o: "bind"